export const REGISTRATION_BEGINS = 'REGISTRATION_BEGINS';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';

export const LOGIN_BEGINS = 'LOGIN_BEGINS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';

export const OPEN_PRESCRIPTION_DETAILS_MODAL = 'OPEN_PRESCRIPTION_DETAILS_MODAL';

export const OPEN_MEDICINE_DETAILS_MODAL = 'OPEN_PRESCRIPTION_DETAILS_MODAL';

export const OPEN_FILTER_MODAL = 'OPEN_FILTER_MODAL';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';